# Git

`git init` - инициализировать репозиторий

`git add .` - добавить все файлы к отслеживанию

`git commit -m "commit message"` - сделать коммит с названием commit message

`git push origin master` - сделать пуш в удаленный репозиторий origin в ветку master

`git pull` - подтянуть изменения

`git branch new-feature` - сделать ветку new-feature

`git checkout new-feature` - перейти на ветку new-feature

`git log` - посмотреть историю коммитов

`git log --all --decorate --oneline --graph` - посмотреть красивую историю коммитов

`git checkout 978be83` - перейти к коммиту 978be83

При создании репозитория на github, будут написаны команды как запушить код в первый раз

## Задача

Последовательно сделать следующее:

1. Создать новую папку test_git

2. Инициализировать репозиторий

3. Сделать текстовый файл 1.txt, заполнить его по своему усмотрению

4. Сделать коммит

5. Сделать новую ветку second-file, перейти в нее

6. Закоммитить новый файл 2.txt с произвольным содержимым

7. Перейти к master-ветке, проверить, что файл 2.txt остался в другой ветке

8. Замержить ветку second-file в master

# Anaconda

`conda create -n my-environment python=3.8` - создать окружение my-environment с питоном 3.8

`conda activate my-environment` - активировать окружение

`conda deactivate` - деактивировать окружение

`conda install numpy` - установка библиотеки

`conda env export --name my-environment > env.yml` - экспорт всех библиотек в yml файл

`conda env create --file env.yml` - создать окружение из файла env.yml

# Numpy

numpy позволяет оперировать матрицами и векторами

## Установка

В нужном окружении запустить

```
conda install numpy
```

Импортируем библиотеку

In [457]:
import numpy as np

Создаем массив из обычного списка python

In [458]:
test_list = [1, 2, 3]
array = np.array(test_list)
print(array, array.shape, len(array))

[1 2 3] (3,) 3


Генерируем разные массивы

In [459]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [460]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Создаем матрицу из списка массива

In [461]:
matrix = np.arange(100)
np_matrix = np.array(matrix)
print(np_matrix)
print(np_matrix.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


Пример работы reshape

In [462]:
np_matrix.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [463]:
np_matrix.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],

In [464]:
np_matrix.reshape(-1, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43]],

       [[44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51]],

       [[52, 53],
        [54, 55]],

       [[56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63]],

       [[64, 65],
        [66, 67]],

       [[68, 69],
        [70, 71]],

       [[72, 73],
        [74, 75]],

       [[76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83]],

       [[84, 85],
        [86, 87]],

       [[88, 89],
        [90, 91]],

       [[92, 93],
        [94, 95]],

       [[96, 97],
        [98, 99]]])

## Задача

Сгенерировать вектор из 100 элементов и превратить его в:

- матрицу 10x10
- вектор 1x100
- вектор 100x1

In [465]:
# Ваш код здесь


## Базовые операции

При помощи numpy можно легко делать любые простейшие операции над векторами и матрицами

In [466]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [467]:
a + b

array([20, 31, 42, 53])

In [468]:
b ** 2

array([0, 1, 4, 9])

In [469]:
mask = (b > 2) & (b < 5)
mask

array([False, False, False,  True])

In [470]:
(b > 2)

array([False, False, False,  True])

In [471]:
(b < 5)

array([ True,  True,  True,  True])

Выбираем все элементы меньше двух

In [472]:
b[mask]

array([3])

In [473]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [474]:
A

array([[1, 1],
       [0, 1]])

In [475]:
B

array([[2, 0],
       [3, 4]])

Поэлементное произведение

In [476]:
A * B

array([[2, 0],
       [0, 4]])

Произведение матриц

In [477]:
A @ B

array([[5, 4],
       [3, 4]])

In [478]:
A.dot(B) # тоже самое

array([[5, 4],
       [3, 4]])

Транспонирование

In [479]:
B

array([[2, 0],
       [3, 4]])

In [480]:
B.T

array([[2, 3],
       [0, 4]])

## Задача - Решение СЛАУ

$Ax = b$

Функция обратной матрицы - `np.linalg.inv(A)`

In [481]:
A = np.array([
    [3, -2],
    [5, 1]]
)
b = np.array([-6, 3])
# Решение - [0, 3]

In [482]:
A_inv = np.linalg.inv(A)
A_inv @ b

array([0., 3.])

In [483]:
# Ваш код здесь
A_inv = np.linalg.inv(A)
x = A_inv @ b
x

array([0., 3.])

Проверить себя можно при помощи `np.linalg.solve(A, b)` - функция решения СЛАУ

In [484]:
# Ваш код здесь


Создание случайного массива

In [485]:
rand_arr = np.random.uniform(-1, 1, size=(4, 3))
rand_arr

array([[ 0.65302679, -0.03240677,  0.2080493 ],
       [ 0.7643057 ,  0.42422108,  0.21884328],
       [-0.39770801,  0.69130095, -0.45638533],
       [-0.38854258, -0.18841378, -0.53538786]])

In [486]:
rand_arr[rand_arr < 0]

array([-0.03240677, -0.39770801, -0.45638533, -0.38854258, -0.18841378,
       -0.53538786])

Считаем сумму по строкам/столбцам

In [487]:
rand_arr.sum(axis=0) # столбцы

array([ 0.6310819 ,  0.89470147, -0.56488061])

In [488]:
rand_arr.sum(axis=1) # строки

array([ 0.82866933,  1.40737005, -0.1627924 , -1.11234422])

Находим минимум максимум во всем массиве и по строкам/столбцам

In [489]:
rand_arr.max(), rand_arr.min()

(0.7643056978976814, -0.5353878576592432)

In [490]:
rand_arr.min(axis=1)

array([-0.03240677,  0.21884328, -0.45638533, -0.53538786])

Также можно применять любые математические операции к массиву

In [491]:
np.sqrt([1, 4, 9])

array([1., 2., 3.])

In [492]:
np.exp(rand_arr)

array([[1.92134756, 0.9681127 , 1.23127387],
       [2.14750284, 1.52839945, 1.2446362 ],
       [0.67185818, 1.99631094, 0.63356965],
       [0.67804435, 0.82827191, 0.58544218]])

In [493]:
np.log(rand_arr)

/var/folders/70/_zfvbgld4sx4vqvkf7nw5j0m0000gn/T/ipykernel_64118/772721215.py:1: RuntimeWarning: invalid value encountered in log
  np.log(rand_arr)


array([[-0.42613712,         nan, -1.5699802 ],
       [-0.26878744, -0.85750055, -1.51939943],
       [        nan, -0.36918003,         nan],
       [        nan,         nan,         nan]])

In [494]:
type(4.)

float

## Задача

Сгенерировать случайную матрицу и посчитать сумму положительных элементов в каждой строке, в каждом столбце.

In [495]:
# Ваш код здесь
a = np.random.uniform(-10, 10, (3, 5))
a

array([[ 7.24201567, -1.59472343,  1.43430737, -4.58251868,  4.57236249],
       [-6.01294688, -6.58465397,  4.25002521, -6.57959828,  8.01312585],
       [ 0.4531252 , -6.49118742, -8.00243551,  2.34880908, -8.29470054]])

In [496]:
a_only_positive = a * (a > 0)
a_only_positive

array([[ 7.24201567, -0.        ,  1.43430737, -0.        ,  4.57236249],
       [-0.        , -0.        ,  4.25002521, -0.        ,  8.01312585],
       [ 0.4531252 , -0.        , -0.        ,  2.34880908, -0.        ]])

In [497]:
a_only_positive.sum(axis=0), a_only_positive.sum(axis=1)

(array([ 7.69514088,  0.        ,  5.68433259,  2.34880908, 12.58548834]),
 array([13.24868553, 12.26315106,  2.80193429]))

In [498]:
a

array([[ 7.24201567, -1.59472343,  1.43430737, -4.58251868,  4.57236249],
       [-6.01294688, -6.58465397,  4.25002521, -6.57959828,  8.01312585],
       [ 0.4531252 , -6.49118742, -8.00243551,  2.34880908, -8.29470054]])

In [499]:
min_ = a.min()
max_ = a.max()

b = (a - min_) / (max_ - min_)
b

array([[0.95271533, 0.41084427, 0.5965852 , 0.22763192, 0.78901153],
       [0.13991771, 0.10486048, 0.76924573, 0.1051705 , 1.        ],
       [0.53641887, 0.11059188, 0.01792177, 0.65266268, 0.        ]])

In [500]:
def min_max_scaler(array: np.ndarray) -> np.ndarray:
    min_ = array.min()
    max_ = array.max()

    return (array - min_) / (max_ - min_)

In [501]:
min_max_scaler(a)

array([[0.95271533, 0.41084427, 0.5965852 , 0.22763192, 0.78901153],
       [0.13991771, 0.10486048, 0.76924573, 0.1051705 , 1.        ],
       [0.53641887, 0.11059188, 0.01792177, 0.65266268, 0.        ]])

In [502]:
b = np.random.normal(0, 1, (10, 10))
min_max_scaler(b)


array([[0.46890123, 0.4962833 , 0.19528098, 0.84350668, 0.70750375,
        0.60490694, 0.53364571, 0.57969078, 0.31603854, 0.1432252 ],
       [0.37523879, 0.63140891, 0.08408311, 0.42877592, 0.49561889,
        0.60337953, 0.25558586, 0.60434482, 0.59596268, 0.154324  ],
       [0.69069589, 0.33256902, 0.77509108, 0.31768001, 0.44275819,
        0.55836632, 0.82721694, 0.10617185, 0.39636194, 0.32725259],
       [0.4831326 , 0.47205045, 0.32445013, 0.30948692, 0.0825367 ,
        0.64796591, 0.76383087, 0.51057744, 0.44762187, 0.48940883],
       [0.56565397, 0.37677552, 0.91526424, 0.68426326, 0.54317166,
        0.43708551, 0.29236368, 0.54802019, 0.56140365, 0.56405482],
       [0.46389052, 0.19448387, 0.11909697, 0.17419926, 0.21362972,
        0.55615702, 0.4917709 , 0.01931954, 0.62309627, 0.33935986],
       [0.41182112, 0.80156971, 0.68886382, 0.60424824, 0.65859744,
        0.40897216, 0.22600814, 0.66911078, 0.60511192, 0.59474219],
       [0.26741727, 0.64658139, 0.2063990

In [503]:
def sum(a: int, b: int) -> int:
    return a + b

In [504]:
sum("123", "asdzx")

'123asdzx'

## Индексация

Индексация по массивам numpy похожа на индексацию по спискам python, но шире и гибче

Общий синтаксис:

`a[start:stop:step]`

Аргументы можно пропускать, тогда будут взятые аргументы по-умолчанию. Например:

`a[:] == a[0:len(a):1]`

In [505]:
a = np.arange(10) + 5
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Выбираем один элемент

In [506]:
a[2]

7

Берем подмассив

In [507]:
a[2:5]

array([7, 8, 9])

Подмассив с заданным шагом

In [508]:
a[:6:2]

array([5, 7, 9])

In [509]:
a[:6:2] = 1000
a

array([1000,    6, 1000,    8, 1000,   10,   11,   12,   13,   14])

In [510]:
a[a == 1000] = 0
a

array([ 0,  6,  0,  8,  0, 10, 11, 12, 13, 14])

In [511]:
a[::-1]

array([14, 13, 12, 11, 10,  0,  8,  0,  6,  0])

Возьмем матрицу из случайных целых чисел

In [512]:
array = np.random.randint(1, 5, size=(3, 5))
array

array([[3, 1, 2, 1, 2],
       [3, 3, 1, 2, 1],
       [2, 1, 3, 4, 3]])

In [513]:
array[2]

array([2, 1, 3, 4, 3])

По матрицам можно индексироваться отдельно по каждой оси через запятую

Сначала указываем индекс для строк, потом для колонок

In [514]:
array

array([[3, 1, 2, 1, 2],
       [3, 3, 1, 2, 1],
       [2, 1, 3, 4, 3]])

In [515]:
array[:, 1::2]

array([[1, 1],
       [3, 2],
       [1, 4]])

In [516]:
array[0:2, 1:4]

array([[1, 2, 1],
       [3, 1, 2]])

In [517]:
array[::-1, ::2] = 0
array

array([[0, 1, 0, 1, 0],
       [0, 3, 0, 2, 0],
       [0, 1, 0, 4, 0]])

In [518]:
array[-1]

array([0, 1, 0, 4, 0])

In [519]:
array[:, :]

array([[0, 1, 0, 1, 0],
       [0, 3, 0, 2, 0],
       [0, 1, 0, 4, 0]])

Генерируем матрицы

In [520]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [521]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [522]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Задача

Вывести матрицу из нулей и единиц в шахматном порядке

In [523]:
# Ваш код здесь
a = np.zeros((10, 10))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [524]:
a = np.zeros((81,))
a[1::2] = 1
a.reshape((9, 9))

array([[0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0.]])

## Расширяем массивы

In [525]:
a = np.arange(10)
b = a + 1

In [526]:
a.shape, b.shape

((10,), (10,))

In [527]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [528]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Соединям по горизонтали

In [529]:
np.hstack((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

Соединяем по вертикали

In [530]:
np.vstack((a, b))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [531]:
np.hstack((a, [1]))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

Расширение массива в numpy происходит путем создания нового массива.

Поэтому если требуется сгенерировать массив, то лучше сделать это через список, а дальше сделать из него массив numpy

In [532]:
%%timeit

a = np.arange(10)
for i in range(1000):
    a = np.hstack((a, 1))
a.shape

3.44 ms ± 60.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [533]:
%%timeit

a = list(range(10))
for i in range(1000):
    a.append(i)
np.array(a).shape

106 µs ± 735 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Сравниваем скорость list и np.array

# Pandas

 Позволяет работать с данными - читать, преобразовывать и сохранять

 ## Установка

 ```
 conda install pandas
 ```

In [534]:
import pandas as pd

## Series

Series - столбец в таблице.

Он состоит из индекса ("имена" строк) и значений. По-умолчанию индекс - уникальные числа от 0 до длины списка.

Создавать series можно из списка или массива numpy. 

In [535]:
series = pd.Series([1, 2, 3])
series

0    1
1    2
2    3
dtype: int64

In [536]:
series.index

RangeIndex(start=0, stop=3, step=1)

In [537]:
series.values

array([1, 2, 3])

Индекс может быть строкой

In [538]:
legs_counter = pd.Series([4, 4, 8], index=["cat", "dog", "spider"])
legs_counter

cat       4
dog       4
spider    8
dtype: int64

По series можно индексирования при помощи `loc` и `iloc`

- `loc` - если хотим взять по индексу
- `iloc` - если хотим взять по порядковому номеру

In [539]:
legs_counter.iloc[2]

8

In [540]:
legs_counter.loc["dog"]

4

In [541]:
legs_counter.unique()

array([4, 8])

In [542]:
legs_counter.nunique()

2

## DataFrame

DataFrame - набор Series, то есть таблица.

Индекс для датафрейма - названия строк

Колонки - названия столбцов (series)

In [543]:
ages = [25, 35, 45]
heights = [170, 180, 190]
names = ["Alex", "Polina", "Misha"]
data = {'age': ages, 'height': heights, "name": names}
df = pd.DataFrame(data, index=names)
df

age  height    name
Alex     25     170    Alex
Polina   35     180  Polina
Misha    45     190   Misha

In [544]:
df['age']  #Получился Series

Alex      25
Polina    35
Misha     45
Name: age, dtype: int64

In [545]:
df[['age', 'height']] #Получился DataFrame

age  height
Alex     25     170
Polina   35     180
Misha    45     190

In [546]:
df[['age']] # Получился DataFrame

age
Alex     25
Polina   35
Misha    45

Можно добавить новую колонку

In [547]:
df['height/age'] = df['height'] / df['age']
df

age  height    name  height/age
Alex     25     170    Alex    6.800000
Polina   35     180  Polina    5.142857
Misha    45     190   Misha    4.222222

In [548]:
df["age"].sum()
df["age"].min()
df["age"].max()
df["age"].mean()

35.0

Можно взять содержимое датафрейма как набор numpy-массивов

In [549]:
df.values

array([[25, 170, 'Alex', 6.8],
       [35, 180, 'Polina', 5.142857142857143],
       [45, 190, 'Misha', 4.222222222222222]], dtype=object)

Можно фильтровать датафреймы

In [550]:
mask = df['age'] == 25
mask

Alex       True
Polina    False
Misha     False
Name: age, dtype: bool

In [551]:
df[mask]

age  height  name  height/age
Alex   25     170  Alex         6.8

In [552]:
df[df['age'] == 25]

age  height  name  height/age
Alex   25     170  Alex         6.8

In [553]:
t = df[(df['age'] > 35) & (df['height'] > 170)]
t['age'] = 0
t

/var/folders/70/_zfvbgld4sx4vqvkf7nw5j0m0000gn/T/ipykernel_64118/1118647569.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['age'] = 0


age  height   name  height/age
Misha    0     190  Misha    4.222222

In [554]:
df

age  height    name  height/age
Alex     25     170    Alex    6.800000
Polina   35     180  Polina    5.142857
Misha    45     190   Misha    4.222222

Если нужно поменять какое-то значение, можно использовать [.loc](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy)

In [555]:
# mask = df['age'] == 25

# df

In [556]:
df[df['height/age'] > 5]

age  height    name  height/age
Alex     25     170    Alex    6.800000
Polina   35     180  Polina    5.142857

Создадим категорию "высокий", если человек выше 175, а иначе "низкий"

In [557]:
df["height_category"] = df["height"].apply(lambda x: "высокий" if x > 175 else "низкий")
df

age  height    name  height/age height_category
Alex     25     170    Alex    6.800000          низкий
Polina   35     180  Polina    5.142857         высокий
Misha    45     190   Misha    4.222222         высокий

In [558]:
df[(df['height_category'] == "высокий") & (df['age'] > 40)]

age  height   name  height/age height_category
Misha   45     190  Misha    4.222222         высокий

## Задача

Посчитать средний рост для высоких людей

In [559]:
# Ваш код здесь
masked_df = df[df["height_category"] == "высокий"]
masked_df

age  height    name  height/age height_category
Polina   35     180  Polina    5.142857         высокий
Misha    45     190   Misha    4.222222         высокий

In [560]:
masked_df["height"].mean()

185.0

## Пропуски в данных

Часто в реальных данных есть пропуски. Их надо либо убирать, либо заполнять

In [561]:
values = [[None, 1, 2], [None, 2, 3], [None, None, 4]]
df = pd.DataFrame(values, columns=["a", "b", "c"])
df

a    b  c
0  None  1.0  2
1  None  2.0  3
2  None  NaN  4

За удаление отвечает функция `dropna()`

У dropna есть два важных аргумента:

- axis (по-умолчанию 0) - по строкам или по колонкам будем искать наны
- how (по-умолчанию 'any') - бывает any и all, ниже пример использования

Удаляем столбец `a`, потому что в нем все (all) значения None

Сохраним датафрейм, он понадобится ниже

In [562]:
dropped_a = df.dropna(axis=1, how='all')
dropped_a

b  c
0  1.0  2
1  2.0  3
2  NaN  4

Удаляем столбцы `a` и `b`, потому что в них есть None (any)

In [563]:
df.dropna(axis=1, how='any')

c
0  2
1  3
2  4

Возьмем датафрейм выше. Удалим из него последнюю строку, так как в ней есть None

In [564]:
dropped_a.dropna(axis=0, how='any')

b  c
0  1.0  2
1  2.0  3

Заполним пустые значения 0

In [565]:
df.fillna(df["a"].mean())

a    b  c
0  0  1.0  2
1  0  2.0  3
2  0  0.0  4

Заполним последним известным значением

In [566]:
df.fillna(method="ffill")
# Тоже самое, что и df.ffill()

a    b  c
0  None  1.0  2
1  None  2.0  3
2  None  2.0  4

Заполним средним между соседними известными значениями

In [567]:
df.interpolate()

a    b  c
0  None  1.0  2
1  None  2.0  3
2  None  2.0  4

## Работаем с данными

Мы можем прочитать таблицу из разных форматов: Excel, CSV, TSV, HDF и т.д.

Начнем с самого простого формата - CSV. Можно открыть в блокноте файл `data/weather.csv` и посмотреть как он выглядит.

Чтобы загрузить файл в DataFrame, воспользуемся методом `pd.read_csv()`

In [572]:
df = pd.read_csv('https://raw.githubusercontent.com/Shakirov-ER/brunoyam-ds-SC381-2952/main/data/weather.csv')
df.head()

Day   t
0  2008-01-01   0
1  2008-01-02  -5
2  2008-01-03 -11
3  2008-01-04 -11
4  2008-01-05 -12

In [573]:
df.describe()

t
count  3285.000000
mean      8.137595
std      10.403138
min     -23.000000
25%       1.000000
50%       8.000000
75%      17.000000
max      34.000000

In [575]:
type(df.Day.iloc[0])

str

In [576]:
df["Day"] = pd.to_datetime(df["Day"])
df["year"] = df.Day.dt.year
df["month"] = df.Day.dt.month
df["day"] = df.Day.dt.day
df.head()

Day   t  year  month  day
0 2008-01-01   0  2008      1    1
1 2008-01-02  -5  2008      1    2
2 2008-01-03 -11  2008      1    3
3 2008-01-04 -11  2008      1    4
4 2008-01-05 -12  2008      1    5

In [578]:
another_df = pd.DataFrame({'text': ["abc", 'usd']})
another_df

text
0  abc
1  usd

In [580]:
another_df['text'].str.upper()

0    ABC
1    USD
Name: text, dtype: object

## Задача

Вывести среднюю температуру за январь 2010 года

In [584]:
# Ваш код здесь
mask = (df["month"] == 1) & (df["year"] == 2010)
tmp = df[mask]
tmp["t"].mean()


-11.419354838709678

## Группировка и агрегация данных

Иногда нужно объединять строки, в которых есть какие-то одинаковые значения.

Например, мы хотим посчитать среднюю температуру для каждого месяца. Это значит, что нам нужны строки, в которых совпадают year и month

In [586]:
df

Day   t  year  month  day
0    2008-01-01   0  2008      1    1
1    2008-01-02  -5  2008      1    2
2    2008-01-03 -11  2008      1    3
3    2008-01-04 -11  2008      1    4
4    2008-01-05 -12  2008      1    5
...         ...  ..   ...    ...  ...
3280 2016-12-27   1  2016     12   27
3281 2016-12-28  -3  2016     12   28
3282 2016-12-29   0  2016     12   29
3283 2016-12-30   3  2016     12   30
3284 2016-12-31   4  2016     12   31

[3285 rows x 5 columns]

In [590]:
df.groupby(["year", "month"]).mean()

t        day
year month                      
2008 1      -1.612903  16.000000
     2       0.034483  15.000000
     3       1.516129  16.000000
     4       9.566667  15.500000
     5      14.133333  16.333333
...               ...        ...
2016 8      19.161290  16.000000
     9      14.366667  15.500000
     10      5.870968  16.000000
     11     -1.433333  15.500000
     12     -0.806452  16.000000

[108 rows x 2 columns]

Вопрос - почему среднее по дням разное?

Иногда мы хотим применить какую-то функцию, которой нет в стандартном pandas или хотим применить много разных функций к определенным строкам. Для этого существует метод agg (сокращение от Aggregate)

In [595]:
df.groupby(["month"])["t"].agg(['mean', 'max', 'min']) # Применяем много функций ко всем столбцам

mean  max  min
month                     
1      -5.745520    5  -21
2      -3.505882    6  -23
3       0.759857   13  -11
4       7.744444   21   -1
5      15.291367   30    3
6      18.325926   31    9
7      21.949640   33   12
8      19.666667   34   10
9      14.574074   24    5
10      7.326165   16   -2
11      2.466667   11  -13
12     -1.823741    8  -19

In [ ]:
# применяем много функций к определенным столбцам
df.groupby(["month"]).agg({'t':['count','mean','max','min'],'day':['mean']}) 

t                           day
      count       mean max min       mean
month                                    
1       279  -5.745520   5 -21  16.000000
2       255  -3.505882   6 -23  14.670588
3       279   0.759857  13 -11  16.000000
4       270   7.744444  21  -1  15.500000
5       278  15.291367  30   3  16.035971
6       270  18.325926  31   9  15.500000
7       278  21.949640  33  12  15.946043
8       279  19.666667  34  10  16.000000
9       270  14.574074  24   5  15.500000
10      279   7.326165  16  -2  16.000000
11      270   2.466667  11 -13  15.500000
12      278  -1.823741   8 -19  16.000000

In [ ]:
df.groupby(["month"]).agg(
    {'t':[
        ('one',  np.mean), 
        ('two', lambda value: 100 * ((value>32).sum() / value.std())), 
        ('three', lambda value: 100* ((value > 45).sum() / value.mean()))
    ]}
)

t                 
             one        two three
month                            
1      -5.745520   0.000000  -0.0
2      -3.505882   0.000000  -0.0
3       0.759857   0.000000   0.0
4       7.744444   0.000000   0.0
5      15.291367   0.000000   0.0
6      18.325926   0.000000   0.0
7      21.949640  22.633403   0.0
8      19.666667  24.377675   0.0
9      14.574074   0.000000   0.0
10      7.326165   0.000000   0.0
11      2.466667   0.000000   0.0
12     -1.823741   0.000000  -0.0

## Функция map

In [ ]:
month_number_to_name = {
    1: "Январь",
    2: "Февраль",
    3: "Март",
    4: "Апрель",
    5: "Май",
    6: "Июнь",
    7: "Июль",
    8: "Август",
    9: "Сентябрь",
    10: "Октябрь",
    11: "Ноябрь",
    12: "Декабрь"
}

In [ ]:
df["month_name"] = df["month"].map(month_number_to_name)
df.head()

Day   t  year  month  day month_name
0 2008-01-01   0  2008      1    1     Январь
1 2008-01-02  -5  2008      1    2     Январь
2 2008-01-03 -11  2008      1    3     Январь
3 2008-01-04 -11  2008      1    4     Январь
4 2008-01-05 -12  2008      1    5     Январь

Сохраним результаты

## Функций apply

In [ ]:
df['T_f'] = df.t.apply(lambda x: 9/5 * x + 32)
df.head()

Day   t  year  month  day month_name   T_f
0 2008-01-01   0  2008      1    1     Январь  32.0
1 2008-01-02  -5  2008      1    2     Январь  23.0
2 2008-01-03 -11  2008      1    3     Январь  12.2
3 2008-01-04 -11  2008      1    4     Январь  12.2
4 2008-01-05 -12  2008      1    5     Январь  10.4

In [ ]:
df.to_csv('result.csv')

## Задача

**Во всех задачах ниже стараемся избегать циклов**


Найти насколько отличалась температура в самый жаркий и самый холодный день

In [596]:
max_ = df["t"].max()
min_ = df["t"].min()

max_ - min_

57

## Задача

Вывести среднее, максимальное, минимальное, стандартное отклонение и медиану температуры за каждый год

In [597]:
df.groupby("year")["t"].agg(['mean', 'max', 'min'])

mean  max  min
year                    
2008  8.545205   27  -14
2009  7.610959   26  -13
2010  7.117808   34  -23
2011  8.337912   31  -20
2012  6.980822   31  -19
2013  8.728767   31  -16
2014  8.931507   31  -18
2015  9.079452   27  -11
2016  7.907104   30  -21

## Задача

Необходимо узнать насколько медиана отличалась от среднего в каждом месяце. Использовать agg для решения

In [600]:
agg_df = df.groupby(["year", "month"])["t"].agg(["median", "mean"])
agg_df

median       mean
year month                   
2008 1         1.0  -1.612903
     2         0.0   0.034483
     3         1.0   1.516129
     4         9.0   9.566667
     5        13.5  14.133333
...            ...        ...
2016 8        19.0  19.161290
     9        14.5  14.366667
     10        6.0   5.870968
     11       -1.0  -1.433333
     12        0.0  -0.806452

[108 rows x 2 columns]

In [602]:
agg_df["compare"] = np.abs(agg_df["median"] - agg_df["mean"])
agg_df

median       mean   compare
year month                             
2008 1         1.0  -1.612903  2.612903
     2         0.0   0.034483  0.034483
     3         1.0   1.516129  0.516129
     4         9.0   9.566667  0.566667
     5        13.5  14.133333  0.633333
...            ...        ...       ...
2016 8        19.0  19.161290  0.161290
     9        14.5  14.366667  0.133333
     10        6.0   5.870968  0.129032
     11       -1.0  -1.433333  0.433333
     12        0.0  -0.806452  0.806452

[108 rows x 3 columns]

## Задача

Вывести день, в который максимально изменилась температура

Подсказка: `diff()`

In [609]:
# Ваш код здесь
df["difference"] = np.abs(df["t"].diff())
max_index = df["difference"].argmax()
df.iloc[[2335]]

Day  t  year  month  day  difference
2335 2014-05-27  7  2014      5   27        15.0

## Поработаем с экселем

Сохраним датафрейм в эксель

In [ ]:
df.to_excel('../data/excel.xlsx')

Прочитаем из экселя

In [ ]:
pd.read_excel('../data/excel.xlsx', index_col=0)

Day   t  year  month  day month_name   T_f
0    2008-01-01   0  2008      1    1     Январь  32.0
1    2008-01-02  -5  2008      1    2     Январь  23.0
2    2008-01-03 -11  2008      1    3     Январь  12.2
3    2008-01-04 -11  2008      1    4     Январь  12.2
4    2008-01-05 -12  2008      1    5     Январь  10.4
...         ...  ..   ...    ...  ...        ...   ...
3280 2016-12-27   1  2016     12   27    Декабрь  33.8
3281 2016-12-28  -3  2016     12   28    Декабрь  26.6
3282 2016-12-29   0  2016     12   29    Декабрь  32.0
3283 2016-12-30   3  2016     12   30    Декабрь  37.4
3284 2016-12-31   4  2016     12   31    Декабрь  39.2

[3285 rows x 7 columns]

# Полезные ссылки

- [Git](https://git-scm.com/downloads)

- [Anaconda](https://www.anaconda.com/products/individual#Downloads)

- [VS Code](https://code.visualstudio.com/download)

- [Шпаргалка по анаконде](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf)

- [Шпаргалка по гиту](https://education.github.com/git-cheat-sheet-education.pdf)

- [Установка jupyterlab (вариант с conda install, не забываем активировать окружение)](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html)

- [Небольшой курс по numpy-pandas-matplotlib, если хочется интерактивных задач](https://www.sololearn.com/learning/1161)

# Домашняя работа

## Easy

Открыть набор данных dota_hero_stats.csv из папки data. 

Данные взяты [отсюда](https://api.opendota.com/api/heroes), на этом же [сайте](https://www.opendota.com/) можно найти больше разнообразных данных по Dota2.

Пересчитаем число ног у героев игры Dota2! Сгруппируйте героев из датасэта по числу их ног (колонка legs), и посчитайте количество героев для каждого значения legs

## Normal

Продолжим исследование героев Dota2. Сгруппируйте по колонкам attack_type и primary_attr и выберите самый распространённый набор характеристик. Выведите список героев с этим набором характеристик


## Hard

В колонке roles находится список того, к каким ролям приписывают создатели Dota того или иного героя. 
Так же у каждого героя есть его основная характеристика, которая записана в колонке primary_attr.

1) Для каждой роли требуется построить bar plot на котором будет видно какое колличество раз героев с тем или иным основным атрибутам создатели игры относят к данной роли.

2) Так же требуется сделать обратный график: для каждого основного аттрибута сделайте bar plot на котором будет видно какое колличество раз создатели Dota относили героя с этим атрибутом к конкретной роли.

3) Сделайте выводы по полученым графикам (это могут быть совершенно любые выводы)

P.s
Для задания 1 должно получится 12 таких графиков (для каждой роли):

![screen 1](https://raw.githubusercontent.com/Shakirov-ER/brunoyam-ds-SC372-2560/main/images/02-screenshot_1.png)

Для задания 2 должно получится 3 таких графика (для каждого атрибута): 

![screen 2](https://raw.githubusercontent.com/Shakirov-ER/brunoyam-ds-SC372-2560/main/images/02-screenshot_2.png)

p.s.s Задание непростое. Попробуйте сначала сделать сами. Если не получается, то в ноутбуке 02-solution есть подсказка